version: 2
jobs:
  build:
    docker:
      - image: ubuntu-1604:201903-01
    resource_class: gpu.medium
    steps:
      - checkout
      - run:
          name: Setup CI environment
          command: ./scripts/setup_ci.sh
      - run:
          name: Install Deps
          command: ./scripts/install.sh
      - run:
          name: Sanity Check
          command: python3 scripts/sanity_check.py
      - run:
          name: Run Pytorch scripts
          command: ./scripts/run_pytorch.sh

workflows:
  version: 2
  workflow-build:
    jobs:
      - build
